language: node_js
node_js:
  "10.15.1"

jobs:
  include:
    - stage: unit tests
      script: "yarn test"
    - stage: deploy to GitHub pages
      script: "yarn build"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_ACCESS_TOKEN
        local_dir: build
        on:
          master

